// The decision artifact: what TypeScript emits and Python scores.
//
// The split is deliberate and is the same one edge-reco settled on. This side
// PRODUCES the evidence — it drives the real engine over the real corpus and
// records, for every (query, candidate) pair, what the user would have been
// shown. The other side SCORES it: precision, recall, F1, FPR and FNR come from
// `assay` (scikit-learn under a trust envelope), in eval/. Nothing in this
// package computes a metric, because one metric written in two languages will
// diverge and only the rendered number would show it.
//
// The artifact is GENERATED, never committed. It is regenerated by the same
// command that scores it (`gate:decision`), so there is no window in which the
// floors could grade a stale run. What IS committed is the measured metrics and
// their floors — eval/baselines/decision-baseline.json — which is the reviewable
// diff when a change moves the numbers.
//
// JSONL, not JSON: a full run is ~90k pair rows, and a line-per-query file
// streams on the Python side instead of being parsed whole.

import { writeFileSync } from "node:fs";
import type { SegmentReport } from "../recall/report.ts";
import type { DecisionLevel } from "./levels.ts";

/** One retrieved (or expected-but-missing) candidate for one query. */
export interface EmittedCandidate {
	readonly entityId: string;
	/** 1-based rank in the engine's returned order, or null when not retrieved. */
	readonly rank: number | null;
	/** False for an expected entity the engine never surfaced — a hard miss. */
	readonly retrieved: boolean;
	/** Combined score in [0, 1]. 0 for a candidate that was never scored. */
	readonly score: number;
	/** The `name_trigram` signal value the app's lexical gate reads. */
	readonly lexical: number;
	/** Whole-token overlap with the query — the lexical gate's escape hatch. */
	readonly tokenContainment: boolean;
	/** True when this entity is a legitimate answer for this query. */
	readonly expected: boolean;
	/**
	 * The levels at which the user would have been SHOWN this entity, and the
	 * levels at which it would have LED as a primary card.
	 *
	 * The verdicts are computed here, by ./decide, and emitted as facts. The
	 * Python side reads booleans and never restates the rule — a screening
	 * decision expressed in two languages is the failure mode this repository has
	 * already paid for once. ./decide is in turn held to the app's real
	 * `passesStrictness` / `partitionByConfidence` by
	 * frontend/app/src/pages/decisionParity.test.ts.
	 */
	readonly kept: readonly string[];
	readonly primary: readonly string[];
}

/**
 * Which measurement a query belongs to. Segments are never averaged together.
 *
 * The two negative segments are the bounds, not two samples of one thing:
 * `clean-hard` has 100% token overlap with the list and `clean-plain` has none.
 * See ./negatives and ./plainNames.
 */
export type DecisionSegment =
	| "alias"
	| "canonical"
	| "clean-hard"
	| "clean-plain";

/** One screened query and every candidate the decision could have shown. */
export interface EmittedQuery {
	readonly kind: "query";
	readonly id: number;
	readonly segment: DecisionSegment;
	readonly query: string;
	/** Entity ids that legitimately answer this query. Empty for `clean`. */
	readonly expected: readonly string[];
	readonly candidates: readonly EmittedCandidate[];
}

/** What was measured, and with what. */
export interface EmittedHeader {
	readonly kind: "header";
	readonly schemaVersion: 1;
	readonly measuredAt: string;
	readonly engineVersion: string;
	readonly corpus: {
		readonly listId: string;
		readonly entities: number;
		readonly fixture: string;
		readonly fixtureSha256: string;
	};
	readonly retrieval: { readonly threshold: number; readonly k: number };
	readonly levels: readonly DecisionLevel[];
	readonly sample: {
		readonly seed: number;
		readonly perSegment: number;
		readonly availableAlias: number;
		readonly availableCanonical: number;
		readonly cleanHardGenerated: number;
		readonly cleanPlainGenerated: number;
	};
	/**
	 * recall@k for THESE queries, computed by the recall harness's own
	 * `measureSegment` — the hand-written TypeScript that has been the only
	 * measurement in this repository until now.
	 *
	 * It is emitted here to be checked, not to be trusted. The Python side
	 * recomputes the same numbers through `assay` over the emitted ranks and
	 * asserts they agree to full float precision. If the two disagree, the
	 * TypeScript is the suspect: it is the one nobody has ever cross-checked.
	 *
	 * These are NOT the committed recall baseline's numbers. That baseline
	 * screens at the live floor of 0.30 and samples with its own seed; this run
	 * screens at 0 (see ./levels) over a different sample, so recall here is at or
	 * above it. What is being validated is the arithmetic, on identical inputs.
	 */
	readonly recallCheck: readonly SegmentReport[];
}

/** A whole emitted run, header first. */
export interface DecisionArtifact {
	readonly header: EmittedHeader;
	readonly queries: readonly EmittedQuery[];
}

/** Write an artifact as JSONL: the header, then one line per query. */
export function writeArtifact(path: string, artifact: DecisionArtifact): void {
	const lines = [
		JSON.stringify(artifact.header),
		...artifact.queries.map((q) => JSON.stringify(q)),
	];
	writeFileSync(path, `${lines.join("\n")}\n`, "utf8");
}
