plugins {
	id 'org.springframework.boot' version '2.4.1'
	id 'io.spring.dependency-management' version '1.0.10.RELEASE'
	id 'java'
}

group = 'org.gainratio'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '8'

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
	jaxb // Only for generation purpose
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.projectlombok:lombok:1.18.16'
	implementation 'junit:junit:4.12'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

	compile 'org.springframework.data:spring-data-elasticsearch:4.0.0.RELEASE'
	// https://mvnrepository.com/artifact/org.dom4j/dom4j
	compile group: 'org.dom4j', name: 'dom4j', version: '2.1.3'
	compile 'xerces:xercesImpl:2.11.0'

	// https://mvnrepository.com/artifact/commons-io/commons-io
	compile group: 'commons-io', name: 'commons-io', version: '2.6'
	// https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
	compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.11'
	compile 'org.apache.commons:commons-collections4:4.1'
	// https://mvnrepository.com/artifact/commons-codec/commons-codec
	compile group: 'commons-codec', name: 'commons-codec', version: '1.15'
	compile 'org.springdoc:springdoc-openapi-ui:1.5.2'
	// https://mvnrepository.com/artifact/org.apache.commons/commons-text
	compile group: 'org.apache.commons', name: 'commons-text', version: '1.9'


	// https://mvnrepository.com/artifact/org.apache.lucene/lucene-core
	compile group: 'org.apache.lucene', name: 'lucene-core', version: '8.6.2'
	// https://mvnrepository.com/artifact/org.apache.lucene/lucene-backward-codecs
	compile group: 'org.apache.lucene', name: 'lucene-backward-codecs', version: '8.6.2'
// https://mvnrepository.com/artifact/org.apache.lucene/lucene-analyzers-phonetic
	compile group: 'org.apache.lucene', name: 'lucene-analyzers-phonetic', version: '8.6.2'


	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
	useJUnitPlatform()
}

sourceSets {
	main {
		resources {
			srcDirs "data"
		}
	}
}

test{
	minHeapSize = "2g"
	maxHeapSize = "2g"
}