plugins {
	id 'org.springframework.boot' version '2.5.2'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'java'
}

group = 'org.amlfilter'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
	implementation 'org.springframework.data:spring-data-elasticsearch'

	// https://mvnrepository.com/artifact/dom4j/dom4j
	implementation group: 'dom4j', name: 'dom4j', version: '1.6.1'
	// https://mvnrepository.com/artifact/jaxen/jaxen
	implementation group: 'jaxen', name: 'jaxen', version: '1.2.0'

	implementation 'xerces:xercesImpl:2.11.0'

	// https://mvnrepository.com/artifact/commons-io/commons-io
	implementation group: 'commons-io', name: 'commons-io', version: '2.6'
	// https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
	implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.11'
	implementation 'org.apache.commons:commons-collections4:4.1'
	// https://mvnrepository.com/artifact/commons-codec/commons-codec
	implementation group: 'commons-codec', name: 'commons-codec', version: '1.15'
	implementation 'org.springdoc:springdoc-openapi-ui:1.5.2'
	// https://mvnrepository.com/artifact/org.apache.commons/commons-text
	implementation group: 'org.apache.commons', name: 'commons-text', version: '1.9'


	// https://mvnrepository.com/artifact/org.apache.lucene/lucene-core
	implementation group: 'org.apache.lucene', name: 'lucene-core', version: '8.8.0'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
	useJUnitPlatform()
}

sourceSets {
	main {
		resources {
			srcDirs "data"
		}
	}
}

test{
	minHeapSize = "6g"
	maxHeapSize = "6g"
}