server.port=8080
#logging.level.org.springframework=ERROR
springdoc.swagger-ui.path=/swagger-ui-custom.html
sdn.URL=https://www.treasury.gov/ofac/downloads/sanctions/1.0/sdn_advanced.xml
spring.data.mongodb.database=aml-filter
spring.data.mongodb.uri=mongodb://${DB_HOST:localhost}:${DB_PORT:27017}





