server.port=8081
#logging.level.org.springframework=ERROR
springdoc.swagger-ui.path=/swagger-ui-custom.html
sdn.URL=https://www.treasury.gov/ofac/downloads/sdn.xml
eu.URL=https://webgate.ec.europa.eu/europeaid/fsd/fsf/public/files/xmlFullSanctionsList_1_1/content?token=dG9rZW4tMjAxNw
spring.data.mongodb.database=aml-filter
spring.data.mongodb.uri=mongodb://${DB_HOST:localhost}:${DB_PORT:27017}





