server.port=8080
#logging.level.org.springframework=ERROR
logging.level.org.hibernate.SQL=DEBUG
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.initialization-mode=always
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/aml-filter
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.flyway.url=jdbc:postgresql://localhost:5432/aml-filter
spring.flyway.schemas=public
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.baselineOnMigrate=true

sdn.URL=https://www.treasury.gov/ofac/downloads/sanctions/1.0/sdn_advanced.xml






