import {
	type CatalogListInfo,
	configFromEnv,
	EngineRuntime,
} from "@amlfilter/browser";
import { useEffect, useState } from "react";
import { Trans, useTranslation } from "react-i18next";
import { Link } from "react-router";
import { Footer } from "../components/Footer";
import { DEMO_STATS } from "../generated/landing-stats";
import { listName } from "../lib/plainLabels";
import "../styles/landing.css";

// The public marketing landing at "/". No backend, no auth, no model: it pitches
// in-browser screening (/screen) and the local-first KYC workstation (/customers)
// and routes a visitor to whichever they want.
//
// Copy is i18n'd: the display strings live in locales/en/landing.json under the
// "landing" namespace, and the data arrays below hold catalog KEYS (resolved via
// t() at render). The big KPI figure line (num/prefix/unit) is DATA, not copy.
//
// HONESTY: every KPI below is a real number, not marketing fiction.
//   • $0 backend infra        — the /screen path makes zero backend calls after sync.
//   • ~{modelSizeMb} MB matcher — GENERATED by scripts/gen-demo-stats.mjs from a
//                                 statSync of public/models/.../model_quantized.onnx.
//   • live list entries       — READ at runtime from the verified signed catalog
//                                 (EngineRuntime.catalogOnlyLists: no model boot,
//                                 no list download — catalog chunk only), so
//                                 the count is whatever is published right now.
//                                 Until it arrives, or if the read fails, the tile
//                                 names the lists without any number — never a
//                                 hard-coded or fixture count.
//   • 0 bytes PII leave       — the query is matched in-tab; nothing typed is sent.

/** The one live read the landing makes: the verified signed list catalog. */
export interface CatalogSource {
	catalogLists(): Promise<ReadonlyArray<CatalogListInfo>>;
	dispose(): Promise<void>;
}

/** Production source: a catalog-only read (the model never boots and no list
 * downloads — the sync is scoped to the signed catalog, ~123 KB on production). */
function engineCatalogSource(): CatalogSource {
	const runtime = new EngineRuntime();
	const config = configFromEnv(import.meta.env);
	return {
		catalogLists: () => runtime.catalogOnlyLists(config),
		dispose: () => runtime.dispose(),
	};
}

interface Metric {
	readonly num: string;
	readonly prefix?: string;
	readonly unit?: string;
	readonly tone?: "hot" | "pos";
	readonly labelKey: string;
	readonly subKey: string;
}

interface Why {
	readonly titleKey: string;
	readonly bodyKey: string;
}

interface Step {
	readonly n: string;
	readonly labelKey: string;
}

const LEADING_METRICS: readonly Metric[] = [
	{
		num: "$0",
		tone: "pos",
		labelKey: "metrics.infra.label",
		subKey: "metrics.infra.sub",
	},
	{
		prefix: "~",
		num: String(DEMO_STATS.modelSizeMb),
		unit: "MB",
		tone: "hot",
		labelKey: "metrics.matcher.label",
		subKey: "metrics.matcher.sub",
	},
];

const TRAILING_METRICS: readonly Metric[] = [
	{
		num: "0 bytes",
		tone: "pos",
		labelKey: "metrics.pii.label",
		subKey: "metrics.pii.sub",
	},
];

const WHYS: readonly Why[] = [
	{ titleKey: "whys.private.title", bodyKey: "whys.private.body" },
	{ titleKey: "whys.local.title", bodyKey: "whys.local.body" },
	{ titleKey: "whys.verifiable.title", bodyKey: "whys.verifiable.body" },
];

const STEPS: readonly Step[] = [
	{ n: "1", labelKey: "howItWorks.steps.sync" },
	{ n: "2", labelKey: "howItWorks.steps.verify" },
	{ n: "3", labelKey: "howItWorks.steps.load" },
	{ n: "4", labelKey: "howItWorks.steps.embed" },
	{ n: "5", labelKey: "howItWorks.steps.score" },
	{ n: "6", labelKey: "howItWorks.steps.rank" },
];

const WORKSTATION_FLOW = [
	"workstation.flow.onboard",
	"workstation.flow.screen",
	"workstation.flow.review",
	"workstation.flow.resolve",
] as const;

function MetricTile({ metric }: { readonly metric: Metric }) {
	const { t } = useTranslation("landing");
	const toneClass = metric.tone ? ` landing__tile-num--${metric.tone}` : "";
	return (
		<div className="landing__tile">
			<div className={`landing__tile-num${toneClass}`}>
				{metric.prefix ? (
					<span className="landing__tile-prefix">{metric.prefix}</span>
				) : null}
				{metric.num}
				{metric.unit ? (
					<span className="landing__tile-unit">{metric.unit}</span>
				) : null}
			</div>
			<div className="landing__tile-label">{t(metric.labelKey)}</div>
			<div className="landing__tile-sub">{t(metric.subKey)}</div>
		</div>
	);
}

function Hero() {
	const { t } = useTranslation("landing");
	return (
		<header className="landing__hero">
			<div className="landing__eyebrow">{t("hero.eyebrow")}</div>
			<div className="landing__wordmark">
				<img src="/logo.svg" alt="" aria-hidden="true" />
				<span className="landing__wordmark-name">
					AML-Filter<span className="landing__wordmark-dot">.</span>
				</span>
			</div>

			<h1 className="landing__title">
				<Trans i18nKey="hero.title" ns="landing" components={{ em: <em /> }} />
			</h1>

			<p className="landing__lede">{t("hero.lede")}</p>
			<p className="landing__audience">{t("hero.audience")}</p>

			<div className="landing__cta">
				<Link to="/screen" className="landing__btn landing__btn--primary">
					{t("hero.ctaPrimary")}
				</Link>
				<Link to="/customers" className="landing__btn landing__btn--ghost">
					{t("hero.ctaSecondary")}
				</Link>
			</div>
			<p className="landing__footnote">{t("hero.footnote")}</p>
		</header>
	);
}

/** The verified catalog, or null while loading / after a failed read. */
function useLiveCatalog(
	makeSource: () => CatalogSource,
): ReadonlyArray<CatalogListInfo> | null {
	const [lists, setLists] = useState<ReadonlyArray<CatalogListInfo> | null>(
		null,
	);
	// Pinned at mount: one catalog read (and one runtime) per landing visit, even
	// if a caller passes a fresh factory on every render.
	const [makeOnce] = useState(() => makeSource);
	useEffect(() => {
		let cancelled = false;
		const source = makeOnce();
		source
			.catalogLists()
			.then((read) => {
				if (!cancelled && read.length > 0) setLists(read);
			})
			// A failed read keeps the number-free statement; nothing to surface.
			.catch(() => undefined);
		return () => {
			cancelled = true;
			void source.dispose().catch(() => undefined);
		};
	}, [makeOnce]);
	return lists;
}

function LiveListsTile({
	lists,
}: {
	readonly lists: ReadonlyArray<CatalogListInfo> | null;
}) {
	const { t, i18n } = useTranslation(["landing", "common"]);
	if (lists === null) {
		return (
			<div className="landing__tile">
				<div className="landing__tile-label">{t("metrics.lists.fallback")}</div>
				<div className="landing__tile-sub">
					{t("metrics.lists.fallbackSub")}
				</div>
			</div>
		);
	}
	const total = lists.reduce((sum, list) => sum + list.entitiesCount, 0);
	const names = lists.map((list) => listName(list.id, t, list.title));
	return (
		<div className="landing__tile">
			<div className="landing__tile-num">
				{new Intl.NumberFormat(i18n.language).format(total)}
			</div>
			<div className="landing__tile-label">
				{t("metrics.lists.label", { count: lists.length })}
			</div>
			<div className="landing__tile-sub">{names.join(" · ")}</div>
		</div>
	);
}

function MetricsBand({
	lists,
}: {
	readonly lists: ReadonlyArray<CatalogListInfo> | null;
}) {
	const { t } = useTranslation("landing");
	return (
		<section className="landing__band" aria-label={t("metrics.ariaLabel")}>
			<div className="landing__band-head">
				<h2 className="landing__band-title">{t("metrics.title")}</h2>
				<div className="landing__band-note">{t("metrics.note")}</div>
			</div>
			<div className="landing__tiles">
				{LEADING_METRICS.map((metric) => (
					<MetricTile key={metric.labelKey} metric={metric} />
				))}
				<LiveListsTile lists={lists} />
				{TRAILING_METRICS.map((metric) => (
					<MetricTile key={metric.labelKey} metric={metric} />
				))}
			</div>
		</section>
	);
}

function WhyCards() {
	const { t } = useTranslation("landing");
	return (
		<section className="landing__why" aria-label={t("whys.ariaLabel")}>
			{WHYS.map((why) => (
				<article key={why.titleKey} className="landing__why-card">
					<div className="landing__why-key">{t(why.titleKey)}</div>
					<div className="landing__why-desc">{t(why.bodyKey)}</div>
				</article>
			))}
		</section>
	);
}

function HowItWorks() {
	const { t } = useTranslation("landing");
	return (
		<section className="landing__how" aria-label={t("howItWorks.ariaLabel")}>
			<div className="landing__how-title">{t("howItWorks.title")}</div>
			<ol className="landing__steps">
				{STEPS.map((step, i) => (
					<li key={step.n} className="landing__step-item">
						<span className="landing__step">
							<b>{step.n}</b>
							{t(step.labelKey)}
						</span>
						{i < STEPS.length - 1 ? (
							<span className="landing__arrow" aria-hidden="true">
								→
							</span>
						) : null}
					</li>
				))}
			</ol>
		</section>
	);
}

function Workstation() {
	const { t } = useTranslation("landing");
	return (
		<section
			className="landing__workstation"
			aria-label={t("workstation.ariaLabel")}
		>
			<div className="landing__workstation-kicker">
				{t("workstation.kicker")}
			</div>
			<h2 className="landing__workstation-title">{t("workstation.title")}</h2>
			<p className="landing__workstation-lede">{t("workstation.lede")}</p>
			<ol className="landing__workstation-flow">
				{WORKSTATION_FLOW.map((flowKey, i) => (
					<li key={flowKey} className="landing__workstation-step">
						<span className="landing__workstation-pill">{t(flowKey)}</span>
						{i < WORKSTATION_FLOW.length - 1 ? (
							<span className="landing__workstation-arrow" aria-hidden="true">
								→
							</span>
						) : null}
					</li>
				))}
			</ol>
			<Link to="/customers" className="landing__btn landing__btn--invert">
				{t("workstation.cta")}
			</Link>
		</section>
	);
}

export function LandingPage({
	catalogSource = engineCatalogSource,
}: {
	readonly catalogSource?: () => CatalogSource;
} = {}) {
	const lists = useLiveCatalog(catalogSource);
	return (
		<main className="landing">
			<div className="landing__wrap">
				<Hero />
				<MetricsBand lists={lists} />
				<WhyCards />
				<HowItWorks />
				<Workstation />
				<Footer />
			</div>
		</main>
	);
}
