// Tests for the landing-stats generator prebuild script. The landing page's one
// build-time KPI (the in-browser matcher's size) is GENERATED from the committed
// ONNX file, not hand-copied — so it can never silently drift. The sanctions
// entry count is NOT generated: the page reads it live from the signed catalog,
// so this script must not emit any list/entity count (a fixture count once sat
// on the public landing as "8 sanctions entities on the demo list").
//
// No mock theater: the pure functions take numbers and we assert exact outputs;
// the I/O paths run against a real temp dir.

import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
	bytesToMb,
	computeStats,
	generateStats,
	modelPath,
	outputPath,
	renderModule,
} from "./gen-demo-stats.mjs";

describe("bytesToMb", () => {
	it("converts bytes to whole MB (decimal, 1e6)", () => {
		// 22,972,370 bytes is the committed quantized ONNX → ~23 MB.
		expect(bytesToMb(22_972_370)).toBe(23);
	});

	it("rounds to the nearest whole MB", () => {
		expect(bytesToMb(1_400_000)).toBe(1);
		expect(bytesToMb(1_600_000)).toBe(2);
	});
});

describe("computeStats", () => {
	it("derives only the model size — no fixture entity count", () => {
		expect(computeStats(22_972_370)).toEqual({ modelSizeMb: 23 });
	});
});

describe("renderModule", () => {
	it("emits a do-not-edit header and the typed named export", () => {
		const src = renderModule({ modelSizeMb: 23 });
		expect(src).toContain("GENERATED by scripts/gen-demo-stats.mjs");
		expect(src).toContain("do not edit");
		expect(src).toContain("export interface DemoStats");
		expect(src).toContain("export const DEMO_STATS: DemoStats");
		expect(src).toContain("modelSizeMb: 23");
	});

	it("emits no 'any' and no demo entity count", () => {
		const src = renderModule({ modelSizeMb: 9 });
		expect(src).not.toContain(": any");
		expect(src).not.toMatch(/demoEntityCount|demo list/i);
	});
});

describe("source paths (single source of truth)", () => {
	it("downloads the model before test stats are generated", async () => {
		const packagePath = join(dirname(outputPath()), "..", "..", "package.json");
		const packageJson = JSON.parse(await readFile(packagePath, "utf8"));
		const prepare =
			"pnpm run download-model && node scripts/gen-demo-stats.mjs";
		expect(packageJson.scripts.pretest).toBe(prepare);
		expect(packageJson.scripts["pretest:coverage"]).toBe(prepare);
	});

	it("modelPath points at the quantized ONNX under public/models", () => {
		expect(
			modelPath().endsWith(
				join(
					"public",
					"models",
					"Xenova",
					"all-MiniLM-L6-v2",
					"onnx",
					"model_quantized.onnx",
				),
			),
		).toBe(true);
	});

	it("outputPath lands the generated module in src/generated", () => {
		expect(
			outputPath().endsWith(join("src", "generated", "landing-stats.ts")),
		).toBe(true);
	});
});

describe("generateStats (I/O, fail-loud)", () => {
	let dir: string;
	beforeEach(async () => {
		dir = await mkdtemp(join(tmpdir(), "gen-stats-"));
	});
	afterEach(async () => {
		await rm(dir, { recursive: true, force: true });
	});

	it("writes the generated module from the real model file", async () => {
		const model = join(dir, "model_quantized.onnx");
		const outPath = join(dir, "landing-stats.ts");
		await writeFile(model, new Uint8Array(2_000_000));

		const stats = await generateStats({ modelPath: model, outPath });

		expect(stats).toEqual({ modelSizeMb: 2 });
		const written = await readFile(outPath, "utf8");
		expect(written).toContain("modelSizeMb: 2");
		expect(written).not.toContain("demoEntityCount");
	});

	it("fails loudly when the model file is missing (no fake number)", async () => {
		await expect(
			generateStats({
				modelPath: join(dir, "missing.onnx"),
				outPath: join(dir, "out.ts"),
			}),
		).rejects.toThrow(/model|missing/i);
	});
});
