// Tests for the demo-stats generator prebuild script. The landing page's
// "real / measured" KPIs (demo entity count, model size) are GENERATED from the
// actual source files by this script, not hand-copied — so the numbers can never
// silently drift. These tests pin the pure derivation logic (count, byte→MB,
// the emitted module text) plus the fail-loud behavior on a missing source file.
//
// No mock theater: the pure functions take strings/bytes and we assert exact
// outputs; the I/O paths run against a real temp dir.

import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
	bytesToMb,
	computeStats,
	countEntities,
	demoEntitiesPath,
	generateStats,
	modelPath,
	outputPath,
	renderModule,
} from "./gen-demo-stats.mjs";

describe("countEntities", () => {
	it("counts one record per non-empty JSONL line", () => {
		const jsonl = '{"a":1}\n{"a":2}\n{"a":3}\n';
		expect(countEntities(jsonl)).toBe(3);
	});

	it("ignores blank and whitespace-only lines", () => {
		const jsonl = '{"a":1}\n\n   \n{"a":2}\n';
		expect(countEntities(jsonl)).toBe(2);
	});

	it("handles a file with no trailing newline", () => {
		expect(countEntities('{"a":1}\n{"a":2}')).toBe(2);
	});
});

describe("bytesToMb", () => {
	it("converts bytes to whole MB (decimal, 1e6)", () => {
		// 22,972,370 bytes is the committed quantized ONNX → ~23 MB.
		expect(bytesToMb(22_972_370)).toBe(23);
	});

	it("rounds to the nearest whole MB", () => {
		expect(bytesToMb(1_400_000)).toBe(1);
		expect(bytesToMb(1_600_000)).toBe(2);
	});
});

describe("computeStats", () => {
	it("combines the entity count and model size into a typed DemoStats", () => {
		const stats = computeStats('{"a":1}\n{"a":2}\n', 22_972_370);
		expect(stats).toEqual({ demoEntityCount: 2, modelSizeMb: 23 });
	});
});

describe("renderModule", () => {
	it("emits a do-not-edit header and the typed named export", () => {
		const src = renderModule({ demoEntityCount: 8, modelSizeMb: 23 });
		expect(src).toContain("GENERATED by scripts/gen-demo-stats.mjs");
		expect(src).toContain("do not edit");
		expect(src).toContain("export interface DemoStats");
		expect(src).toContain("export const DEMO_STATS: DemoStats");
		expect(src).toContain("demoEntityCount: 8");
		expect(src).toContain("modelSizeMb: 23");
	});

	it("emits a module that has no 'any' and reads back the values", async () => {
		const src = renderModule({ demoEntityCount: 5, modelSizeMb: 9 });
		expect(src).not.toContain(": any");
	});
});

describe("source paths (single source of truth)", () => {
	it("demoEntitiesPath points at the committed demo sanctions list", async () => {
		const p = demoEntitiesPath();
		expect(
			p.endsWith(
				join(
					"packages",
					"amlfilter-publisher",
					"fixtures",
					"demo_entities.jsonl",
				),
			),
		).toBe(true);
		// The advertised source must actually exist in the repo with records —
		// this is the file the landing page's entity count is derived from.
		const text = await readFile(p, "utf8");
		expect(countEntities(text)).toBeGreaterThan(0);
	});

	it("modelPath points at the quantized ONNX under public/models", () => {
		expect(
			modelPath().endsWith(
				join(
					"public",
					"models",
					"Xenova",
					"all-MiniLM-L6-v2",
					"onnx",
					"model_quantized.onnx",
				),
			),
		).toBe(true);
	});

	it("outputPath lands the generated module in src/generated", () => {
		expect(
			outputPath().endsWith(join("src", "generated", "landing-stats.ts")),
		).toBe(true);
	});
});

describe("generateStats (I/O, fail-loud)", () => {
	let dir: string;
	beforeEach(async () => {
		dir = await mkdtemp(join(tmpdir(), "gen-stats-"));
	});
	afterEach(async () => {
		await rm(dir, { recursive: true, force: true });
	});

	it("writes the generated module from the real source files", async () => {
		const jsonlPath = join(dir, "demo_entities.jsonl");
		const modelPath = join(dir, "model_quantized.onnx");
		const outPath = join(dir, "landing-stats.ts");
		await writeFile(jsonlPath, '{"a":1}\n{"a":2}\n{"a":3}\n');
		await writeFile(modelPath, new Uint8Array(2_000_000));

		const stats = await generateStats({ jsonlPath, modelPath, outPath });

		expect(stats).toEqual({ demoEntityCount: 3, modelSizeMb: 2 });
		const written = await readFile(outPath, "utf8");
		expect(written).toContain("demoEntityCount: 3");
		expect(written).toContain("modelSizeMb: 2");
	});

	it("fails loudly when the entities file is missing (no fake number)", async () => {
		const modelPath = join(dir, "model_quantized.onnx");
		await writeFile(modelPath, new Uint8Array(2_000_000));
		await expect(
			generateStats({
				jsonlPath: join(dir, "missing.jsonl"),
				modelPath,
				outPath: join(dir, "out.ts"),
			}),
		).rejects.toThrow(/demo_entities|missing/i);
	});

	it("fails loudly when the model file is missing (no fake number)", async () => {
		const jsonlPath = join(dir, "demo_entities.jsonl");
		await writeFile(jsonlPath, '{"a":1}\n');
		await expect(
			generateStats({
				jsonlPath,
				modelPath: join(dir, "missing.onnx"),
				outPath: join(dir, "out.ts"),
			}),
		).rejects.toThrow(/model|missing/i);
	});
});
